name: Demo Workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Get python
        uses: actions/setup-python@v3.12
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverege run test/test_sum_two.py
      - name: Tests report
        run: coverage report
