name: Demo Workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matryx:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Set up python ${{matryx.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matryx.python-version}}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverege run test/test_sum_two.py
      - name: Tests report
        run: coverage report
